# Generated by Django 4.1.2 on 2022-11-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_minuman_jenis_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minuman',
            old_name='jenis_id',
            new_name='jeniss_id',
        ),
    ]
