# Generated by Django 4.1.2 on 2023-02-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minuman',
            old_name='kodemnm',
            new_name='kodeminuman',
        ),
    ]
