# Generated by Django 4.1.2 on 2023-02-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_kodemnm_minuman_kodeminuman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='jeniss_id',
            new_name='jenisss_id',
        ),
    ]
