# Generated by Django 4.1.2 on 2023-02-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_jenisss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='jenisss_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenisss'),
        ),
    ]
